<a href="https://colab.research.google.com/github/Ritumahour/NP_assignment-/blob/main/Copy_of_Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr)

[0 1 2 3 4 5]


2. Given a NumPy array 'arr', check if its data type is float64.


In [ ]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
arr = np.array([1+2j, 2+3j, 3+4j], dtype='complex128')

In [ ]:
arr

array([1.+2.j, 2.+3.j, 3.+4.j])

4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
import numpy as np

# Example integer array
arr = np.array([1, 2, 3, 4, 5])

# Convert to float32
arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)

[1. 2. 3. 4. 5.]
float32


5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
import numpy as np

# Example float64 array
arr = np.array([1.123456789, 2.987654321, 3.141592653589793], dtype=np.float64)

# Convert to float32
arr_float32 = arr.astype(np.float32)

print("Original array (float64):", arr)
print("Converted array (float32):", arr_float32)
print("Data type of converted array:", arr_float32.dtype)

Original array (float64): [1.12345679 2.98765432 3.14159265]
Converted array (float32): [1.1234568 2.9876542 3.1415927]
Data type of converted array: float32


6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.


In [ ]:
import numpy as np

def array_attributes(arr):
    """
    Takes a NumPy array as input and returns its shape, size, and data type.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the shape, size, and data type of the array.
    """
    return arr.shape, arr.size, arr.dtype

# Example usage
example_array = np.array([[1, 2, 3], [4, 5, 6]])
attributes = array_attributes(example_array)
print(f"Shape: {attributes[0]}, Size: {attributes[1]}, Data type: {attributes[2]}")

Shape: (2, 3), Size: 6, Data type: int64


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [ ]:
import numpy as np

def array_dimension(arr):
    """
    Takes a NumPy array as input and returns its dimensionality.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        int: The number of dimensions (dimensionality) of the array.
    """
    return arr.ndim

# Example usage
example_array = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(example_array)
print(f"Dimensionality: {dimension}")

Dimensionality: 2


8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [ ]:
import numpy as np

def item_size_info(arr):
    """
    Takes a NumPy array as input and returns the item size and the total size in bytes.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the item size (in bytes) and the total size (in bytes).
    """
    return arr.itemsize, arr.nbytes

# Example usage
example_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
item_size, total_size = item_size_info(example_array)
print(f"Item size: {item_size} bytes, Total size: {total_size} bytes")

Item size: 4 bytes, Total size: 24 bytes


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
import numpy as np

def array_strides(arr):
    """
    Takes a NumPy array as input and returns its strides.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the strides of the array.
    """
    return arr.strides

# Example usage
example_array = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(example_array)
print(f"Strides: {strides}")

Strides: (24, 8)


10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [ ]:
import numpy as np

def shape_stride_relationship(arr):
    """
    Takes a NumPy array as input and returns its shape and strides.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the shape and strides of the array.
    """
    return arr.shape, arr.strides

# Example usage
example_array = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(example_array)
print(f"Shape: {shape}, Strides: {strides}")

Shape: (2, 3), Strides: (24, 8)


11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [ ]:
import numpy as np

def create_zeros_array(n):
    """
    Creates a NumPy array of zeros with n elements.

    Parameters:
        n (int): Number of elements in the array.

    Returns:
        numpy.ndarray: A NumPy array of zeros with n elements.
    """
    return np.zeros(n)

# Example usage
zeros_array = create_zeros_array(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [ ]:
import numpy as np

def create_ones_matrix(rows, cols):
    """
    Creates a 2D NumPy array filled with ones of size rows x cols.

    Parameters:
        rows (int): Number of rows in the matrix.
        cols (int): Number of columns in the matrix.

    Returns:
        numpy.ndarray: A 2D NumPy array filled with ones.
    """
    return np.ones((rows, cols))

# Example usage
ones_matrix = create_ones_matrix(3, 4)
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step

In [ ]:
import numpy as np

def generate_range_array(start, stop, step):
    """
    Creates a NumPy array with a range starting from start, ending at stop (exclusive),
    and with the specified step.

    Parameters:
        start (int): The starting value of the range.
        stop (int): The stopping value of the range (exclusive).
        step (int): The step size between consecutive values.

    Returns:
        numpy.ndarray: A NumPy array containing the generated range.
    """
    return np.arange(start, stop, step)

# Example usage
range_array = generate_range_array(0, 10, 2)
print(range_array)

[0 2 4 6 8]


14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [ ]:
import numpy as np

def generate_linear_space(start, stop, num):
    """
    Generates a NumPy array with num equally spaced values between start and stop (inclusive).

    Parameters:
        start (float): The starting value of the range.
        stop (float): The ending value of the range.
        num (int): The number of equally spaced values to generate.

    Returns:
        numpy.ndarray: A NumPy array with num equally spaced values between start and stop.
    """
    return np.linspace(start, stop, num)

# Example usage
linear_space = generate_linear_space(0, 1, 5)
print(linear_space)

[0.   0.25 0.5  0.75 1.  ]


15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye

In [ ]:
import numpy as np

def create_identity_matrix(n):
    """
    Creates a square identity matrix of size n x n.

    Parameters:
        n (int): The size of the identity matrix.

    Returns:
        numpy.ndarray: A square identity matrix of size n x n.
    """
    return np.eye(n)

# Example usage
identity_matrix = create_identity_matrix(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


16. Write a function that takes a Python list and converts it into a NumPy array.


In [ ]:
import numpy as np

def list_to_numpy_array(py_list):
    """
    Converts a Python list into a NumPy array.

    Parameters:
        py_list (list): The Python list to convert.

    Returns:
        numpy.ndarray: The converted NumPy array.
    """
    return np.array(py_list)

# Example usage:
python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print("NumPy Array:", numpy_array)

NumPy Array: [1 2 3 4 5]


17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.


In [ ]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Create a new view of the original array
view_array = original_array.view()

# Modify the view and observe the effect on the original array
print("Original Array:", original_array)
print("View Array:", view_array)

# Changing a value in the view
view_array[0] = 99
print("\nAfter modifying the view:")
print("Original Array:", original_array)
print("View Array:", view_array)

# Check if they share the same memory
print("\nDo the arrays share the same memory? ", original_array.base is None)
print("View's base is Original Array? ", view_array.base is original_array)

Original Array: [1 2 3 4 5]
View Array: [1 2 3 4 5]

After modifying the view:
Original Array: [99  2  3  4  5]
View Array: [99  2  3  4  5]

Do the arrays share the same memory?  True
View's base is Original Array?  True


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    """
    Concatenates two NumPy arrays along a specified axis.

    Parameters:
        array1 (numpy.ndarray): The first NumPy array.
        array2 (numpy.ndarray): The second NumPy array.
        axis (int): The axis along which to concatenate. Default is 0.

    Returns:
        numpy.ndarray: The concatenated NumPy array.

    Raises:
        ValueError: If the arrays cannot be concatenated along the specified axis.
    """
    try:
        return np.concatenate((array1, array2), axis=axis)
    except ValueError as e:
        raise ValueError(f"Cannot concatenate arrays along axis {axis}: {e}")

# Example usage
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
result_axis_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", result_axis_0)

# Concatenate along axis 1 (columns)
result_axis_1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1:\n", result_axis_1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.

concatenate`.

In [ ]:
import numpy as np

# Create two NumPy arrays with different shapes
array1 = np.array([[1, 2], [3, 4]])  # Shape: (2, 2)
array2 = np.array([[5], [6]])        # Shape: (2, 1)

# Concatenate them horizontally
concatenated_array = np.concatenate((array1, array2), axis=1)

print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nConcatenated Array:\n", concatenated_array)

Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5]
 [6]]

Concatenated Array:
 [[1 2 5]
 [3 4 6]]


20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
import numpy as np

def vertical_stack_arrays(array_list):
    """
    Vertically stacks multiple NumPy arrays provided in a list.

    Parameters:
        array_list (list of numpy.ndarray): A list of NumPy arrays to stack.

    Returns:
        numpy.ndarray: The vertically stacked array.

    Raises:
        ValueError: If the arrays have mismatched column sizes.
    """
    try:
        return np.vstack(array_list)
    except ValueError as e:
        raise ValueError(f"Cannot vertically stack arrays: {e}")

# Example usage
array1 = np.array([[1, 2], [3, 4]])  # Shape: (2, 2)
array2 = np.array([[5, 6]])          # Shape: (1, 2)
array3 = np.array([[7, 8], [9, 10]]) # Shape: (2, 2)

# Vertically stack the arrays
stacked_array = vertical_stack_arrays([array1, array2, array3])
print("Vertically Stacked Array:\n", stacked_array)

Vertically Stacked Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [ ]:
import numpy as np

def create_array_with_step(start, end, step):
    """
    Creates a NumPy array of integers within a specified range (inclusive)
    with a given step size.

    Parameters:
        start (int): The starting value of the range.
        end (int): The ending value of the range (inclusive).
        step (int): The step size between consecutive elements.

    Returns:
        numpy.ndarray: The resulting array of integers.
    """
    return np.arange(start, end + 1, step)

# Example usage
array = create_array_with_step(1, 10, 2)
print("Array:", array)

Array: [1 3 5 7 9]


22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [ ]:
import numpy as np

def generate_equally_spaced_values():
    """
    Generates an array of 10 equally spaced values between 0 and 1 (inclusive).

    Returns:
        numpy.ndarray: The resulting array of equally spaced values.
    """
    return np.linspace(0, 1, 10)

# Example usage
array = generate_equally_spaced_values()
print("Array of equally spaced values:", array)

Array of equally spaced values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [ ]:
import numpy as np

def generate_logarithmically_spaced_values():
    """
    Generates an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

    Returns:
        numpy.ndarray: The resulting array of logarithmically spaced values.
    """
    return np.logspace(0, 3, 5)

# Example usage
array = generate_logarithmically_spaced_values()
print("Logarithmically spaced values:", array)

Logarithmically spaced values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [ ]:
import numpy as np
import pandas as pd

def create_random_dataframe():
    """
    Creates a Pandas DataFrame with 5 rows and 3 columns, where the values
    are random integers between 1 and 100.

    Returns:
        pandas.DataFrame: The resulting DataFrame.
    """
    # Generate a NumPy array with random integers between 1 and 100
    random_array = np.random.randint(1, 101, size=(5, 3))

    # Create a DataFrame from the NumPy array
    df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])
    return df

# Example usage
random_df = create_random_dataframe()
print(random_df)

   Column1  Column2  Column3
0       60       32       33
1       52       62       57
2       48       21       98
3       61       27       13
4       47       62       59


25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
import pandas as pd
import numpy as np

def replace_negatives_with_zeros(df, column_name):
    """
    Replaces all negative values in a specified column of a Pandas DataFrame with zeros.

    Parameters:
        df (pandas.DataFrame): The input DataFrame.
        column_name (str): The name of the column to modify.

    Returns:
        pandas.DataFrame: The modified DataFrame with negative values replaced by zeros.
    """
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage
data = {
    "A": [10, -5, 30, -20],
    "B": [40, 50, -10, 60]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

modified_df = replace_negatives_with_zeros(df, "A")
print("\nModified DataFrame:\n", modified_df)

Original DataFrame:
     A   B
0  10  40
1  -5  50
2  30 -10
3 -20  60

Modified DataFrame:
     A   B
0  10  40
1   0  50
2  30 -10
3   0  60


26. Access the 3rd element from the given NumPy array.


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
third_element = array[2]

print("The 3rd element is:", third_element)


The 3rd element is: 31.622776601683793


27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [ ]:
import numpy as np

# Create a 2D NumPy array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Access the element at index (1, 2)
element = array[1, 2]

print("The element at index (1, 2) is:", element)



The element at index (1, 2) is: 6


28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])
import numpy as np

# Given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Use boolean indexing to extract elements greater than 5
elements_greater_than_5 = arr[arr > 5]

print("Elements greater than 5:", elements_greater_than_5)


Elements greater than 5: [ 8 10  7]


29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Use slicing to extract elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]

print("Elements from index 2 to 5 (inclusive):", sliced_array)

Elements from index 2 to 5 (inclusive): [3 4 5 6]


30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
import numpy as np

# Given 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice the array to extract the desired sub-array
sub_array = arr_2d[0:2, 1:3]

print("Extracted sub-array:\n", sub_array)

Extracted sub-array:
 [[2 3]
 [5 6]]


31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [ ]:
import numpy as np

def extract_elements_with_indices(arr, indices):
    """
    Extracts elements from a given 2D NumPy array in a specific order based on provided indices.

    Parameters:
        arr (numpy.ndarray): The input 2D array.
        indices (list of tuples): A list of (row, column) tuples indicating the elements to extract.

    Returns:
        numpy.ndarray: A 1D array of extracted elements.
    """
    rows, cols = zip(*indices)  # Separate the row and column indices
    return arr[rows, cols]

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Indices to extract: [(0, 1), (1, 2), (2, 0)]
indices = [(0, 1), (1, 2), (2, 0)]
result = extract_elements_with_indices(arr_2d, indices)

print("Extracted elements:", result)

Extracted elements: [2 6 7]


32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing

In [ ]:
import numpy as np

def filter_greater_than_threshold(arr, threshold):
    """
    Filters elements greater than a specified threshold from a 1D NumPy array.

    Parameters:
        arr (numpy.ndarray): The input 1D array.
        threshold (float): The threshold value.

    Returns:
        numpy.ndarray: A new array with elements greater than the threshold.
    """
    return arr[arr > threshold]

# Example usage
array = np.array([1, 5, 8, 3, 10, 7])
threshold = 5

filtered_array = filter_greater_than_threshold(array, threshold)
print("Filtered elements greater than", threshold, ":", filtered_array)

Filtered elements greater than 5 : [ 8 10  7]


33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [ ]:
import numpy as np

def extract_elements_3d(array, indices_x, indices_y, indices_z):
    """
    Extracts specific elements from a 3D NumPy array using separate indices for each dimension.

    Parameters:
        array (numpy.ndarray): The input 3D array.
        indices_x (array-like): Indices for the first dimension (axis 0).
        indices_y (array-like): Indices for the second dimension (axis 1).
        indices_z (array-like): Indices for the third dimension (axis 2).

    Returns:
        numpy.ndarray: A 1D array of extracted elements.
    """
    return array[indices_x, indices_y, indices_z]

# Example usage
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],
                     [[10, 11, 12],
                      [13, 14, 15],
                      [16, 17, 18]],
                     [[19, 20, 21],
                      [22, 23, 24],
                      [25, 26, 27]]])

# Indices for each dimension
indices_x = [0, 1, 2]
indices_y = [1, 2, 0]
indices_z = [2, 1, 0]

extracted_elements = extract_elements_3d(array_3d, indices_x, indices_y, indices_z)
print("Extracted elements:", extracted_elements)

Extracted elements: [ 6 17 19]


34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [ ]:
import numpy as np

def filter_elements_with_conditions(arr, condition1, condition2):
    """
    Filters elements from a 1D NumPy array where both conditions are satisfied.

    Parameters:
        arr (numpy.ndarray): The input 1D array.
        condition1 (callable): A function defining the first condition (e.g., lambda x: x > 5).
        condition2 (callable): A function defining the second condition (e.g., lambda x: x < 10).

    Returns:
        numpy.ndarray: A new array containing elements that satisfy both conditions.
    """
    # Apply both conditions using boolean indexing
    return arr[condition1(arr) & condition2(arr)]

# Example usage
array = np.array([1, 3, 5, 7, 9, 11, 13])
condition1 = lambda x: x > 5
condition2 = lambda x: x < 10

filtered_elements = filter_elements_with_conditions(array, condition1, condition2)
print("Filtered elements:", filtered_elements)

Filtered elements: [7 9]


35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.


In [ ]:
import numpy as np

def extract_elements_2d(array, row_indices, col_indices):
    """
    Extracts elements from a 2D NumPy array using row and column indices.

    Parameters:
        array (numpy.ndarray): The input 2D array.
        row_indices (array-like): Array of row indices.
        col_indices (array-like): Array of column indices.

    Returns:
        numpy.ndarray: A 1D array of extracted elements.
    """
    return array[row_indices, col_indices]

# Example usage
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

# Indices for rows and columns
row_indices = [0, 1, 2]
col_indices = [2, 1, 0]

# Extract elements
extracted_elements = extract_elements_2d(array_2d, row_indices, col_indices)
print("Extracted elements:", extracted_elements)

Extracted elements: [30 50 70]


36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
import numpy as np

# Given array of shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add scalar value of 5 using broadcasting
result = arr + 5

print("Original array:\n", arr)
print("Array after adding 5:\n", result)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding 5:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [ ]:
import numpy as np

# Define the arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr1.T * arr2

print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Result of broadcasting multiplication:\n", result)

Array arr1:
 [[2 3 4]]
Array arr2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Result of broadcasting multiplication:
 [[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [ ]:
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])  # Shape (4, 3)

# Transpose arr2 to match broadcasting requirements
result = arr1.T + arr2

print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Result of broadcasting addition:\n", result)

Array arr1:
 [[1 2 3 4]]
Array arr2:
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Result of broadcasting addition:
 [[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [ ]:
import numpy as np

# Define the arrays
arr1 = np.array([[1],
                 [2],
                 [3]])  # Shape (3, 1)

arr2 = np.array([[10, 20, 30]])  # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Result of broadcasting addition:\n", result)

Array arr1:
 [[1]
 [2]
 [3]]
Array arr2:
 [[10 20 30]]
Result of broadcasting addition:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [ ]:
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)

arr2 = np.array([[10, 20],
                 [30, 40]])  # Shape (2, 2)

# Reshape arr2 to match the shape of arr1 (or vice versa)
# Example: Broadcasting arr2 to (2, 3)
arr2_reshaped = np.broadcast_to(arr2[:, :1], arr1.shape)  # Reshape arr2 to (2, 3)

# Perform element-wise multiplication
result = arr1 * arr2_reshaped

print("Array arr1:\n", arr1)
print("Array arr2 (reshaped):\n", arr2_reshaped)
print("Result of multiplication:\n", result)

Array arr1:
 [[1 2 3]
 [4 5 6]]
Array arr2 (reshaped):
 [[10 10 10]
 [30 30 30]]
Result of multiplication:
 [[ 10  20  30]
 [120 150 180]]


41. Calculate column wise mean for the given array:
    arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)

[2.5 3.5 4.5]


42. Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print(row_max)


[3 6]


43. For the given array, find indices of maximum value in each column. arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
column_max_indices = np.argmax(arr, axis=0)
print(column_max_indices)

[1 1 1]


44. For the given array, apply custom function to calculate moving sum along rows.arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Define the custom moving sum function
def moving_sum_rowwise(arr, window_size):
    result = np.array([np.convolve(row, np.ones(window_size, dtype=int), mode='valid') for row in arr])
    return result

# Apply the function with a window size of 2
window_size = 2
result = moving_sum_rowwise(arr, window_size)
print(result)

[[ 3  5]
 [ 9 11]]


45. In the given array, check if all elements in each column are even.arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if all elements in each column are even
all_even_columns = np.all(arr % 2 == 0, axis=0)
print(all_even_columns)

[False False False]


46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix. original_array = np.array([1, 2, 3, 4, 5, 6])






In [ ]:
import numpy as np

# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Desired dimensions
m, n = 2, 3

# Reshape the array
reshaped_matrix = original_array.reshape(m, n)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


47. Create a function that takes a matrix as input and returns the flattened array.input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
import numpy as np

# Define the function
def flatten_matrix(matrix):
    return matrix.flatten()

# Input matrix
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Call the function
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


48. Write a function that concatenates two given arrays along a specified axis.array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


In [ ]:
import numpy as np

# Define the function
def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

# Input arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Call the function
concatenated_array = concatenate_arrays(array1, array2, axis=0)  # Change axis as needed
print(concatenated_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


49. Create a function that splits an array into multiple sub-arrays along a specified axis.original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [ ]:
import numpy as np

# Define the function
def split_array(array, num_splits, axis=0):
    return np.array_split(array, num_splits, axis=axis)

# Input array
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Call the function
split_sub_arrays = split_array(original_array, num_splits=3, axis=0)  # Change axis and num_splits as needed
for sub_array in split_sub_arrays:
    print(sub_array)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


50. Write a function that inserts and then deletes elements from a given array at specified indices.original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [ ]:
import numpy as np

# Define the function
def insert_and_delete(array, insert_indices, insert_values, delete_indices):
    # Insert elements
    array = np.insert(array, insert_indices, insert_values)

    # Delete elements
    array = np.delete(array, delete_indices)

    return array

# Input array and indices/values to insert and delete
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Call the function
result_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)

[ 1 10  4 11  5]


51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
import numpy as np

# Create arr1 with random integers (e.g., between 1 and 20) and arr2 with integers from 1 to 10
arr1 = np.random.randint(1, 20, size=5)  # Array of random integers with size 5
arr2 = np.arange(1, 11)[:5]  # Array with integers from 1 to 10, taking first 5 elements

# Perform element-wise addition
result = arr1 + arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise addition result:", result)

arr1: [12 12  2  7  3]
arr2: [1 2 3 4 5]
Element-wise addition result: [13 14  5 11  8]


52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:
import numpy as np

# Generate arr1 with sequential integers from 10 to 1 (descending order)
arr1 = np.arange(10, 0, -1)

# Generate arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction
result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise subtraction result:", result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:
import numpy as np

# Create arr1 with random integers (e.g., between 1 and 10) and arr2 with integers from 1 to 5
arr1 = np.random.randint(1, 10, size=5)  # Array of random integers with size 5
arr2 = np.array([1, 2, 3, 4, 5])  # Array with integers from 1 to 5

# Perform element-wise multiplication
result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise multiplication result:", result)

arr1: [5 5 2 5 9]
arr2: [1 2 3 4 5]
Element-wise multiplication result: [ 5 10  6 20 45]


54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
import numpy as np

# Generate arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)  # Even integers from 2 to 10

# Generate arr2 with integers from 1 to 5
arr2 = np.array([1, 2, 3, 4, 5])

# Perform element-wise division
result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise division result:", result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Element-wise division result: [2. 2. 2. 2. 2.]


55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
import numpy as np

# Generate arr1 with integers from 1 to 5
arr1 = np.array([1, 2, 3, 4, 5])

# Generate arr2 with the same numbers reversed
arr2 = arr1[::-1]

# Perform element-wise exponentiation
result = np.power(arr1, arr2)

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise exponentiation result:", result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Element-wise exponentiation result: [ 1 16 27 16  5]


56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
import numpy as np

# Define the function to count occurrences of a substring
def count_substring_occurrences(array, substring):
    return np.sum(np.char.find(array, substring) != -1)

# Input array of strings
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Specify the substring to count
substring = 'hello'

# Call the function and print the result
occurrences = count_substring_occurrences(arr, substring)
print(f"Occurrences of '{substring}':", occurrences)

Occurrences of 'hello': 3


57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
import numpy as np

# Define the function to extract uppercase characters
def extract_uppercase(array):
    # Extract uppercase characters from each string
    return np.array([''.join([char for char in string if char.isupper()]) for string in array])

# Input array of strings
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Call the function and print the result
uppercase_characters = extract_uppercase(arr)
print("Uppercase characters:", uppercase_characters)

Uppercase characters: ['H' 'W' 'OAI' 'GPT']


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
import numpy as np

# Define the function to replace substrings
def replace_substring(array, old_substring, new_substring):
    return np.char.replace(array, old_substring, new_substring)

# Input array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Specify the substring to replace and the new substring
old_substring = 'apple'
new_substring = 'orange'

# Call the function and print the result
replaced_array = replace_substring(arr, old_substring, new_substring)
print("Replaced array:", replaced_array)

Replaced array: ['orange' 'banana' 'grape' 'pineorange']


59. Write a function that concatenates strings in a NumPy array element-wise.arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [ ]:
import numpy as np

# Define the function to concatenate strings element-wise
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

# Input arrays
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Call the function and print the result
concatenated_array = concatenate_strings(arr1, arr2)
print("Concatenated array:", concatenated_array)

Concatenated array: ['HelloOpen' 'WorldAI']


60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])





In [ ]:
import numpy as np

# Define the function to find the length of the longest string
def longest_string_length(array):
    # Compute the length of each string
    lengths = np.char.str_len(array)
    # Return the maximum length
    return np.max(lengths)

# Input array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Call the function and print the result
longest_length = longest_string_length(arr)
print("Length of the longest string:", longest_length)

Length of the longest string: 9


61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [ ]:
# Generate a dataset of 100 random integers between 1 and 1000
np.random.seed(42)  # For reproducibility
random_dataset = np.random.randint(1, 1001, 100)

# Compute statistical metrics
mean_value = np.mean(random_dataset)
median_value = np.median(random_dataset)
variance_value = np.var(random_dataset)
std_deviation_value = np.std(random_dataset)

# Display the results
mean_value, median_value, variance_value, std_deviation_value


(474.79, 463.5, 81245.46590000001, 285.0359028262931)

62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.




In [ ]:
# Re-import necessary library after execution state reset
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
np.random.seed(42)  # For reproducibility
random_numbers = np.random.randint(1, 101, 50)

# Calculate the 25th and 75th percentiles
percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)

# Display the results
percentile_25, percentile_75


(25.5, 74.5)

63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [ ]:
# Generate two random arrays representing two sets of variables
np.random.seed(42)  # For reproducibility
array1 = np.random.randint(1, 100, 50)
array2 = np.random.randint(1, 100, 50)

# Compute the correlation coefficient matrix
correlation_matrix = np.corrcoef(array1, array2)

# Extract the correlation coefficient
correlation_coefficient = correlation_matrix[0, 1]

# Display the result
correlation_coefficient


-0.1156682265480604

64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.




In [ ]:
# Generate two random matrices (3x3)
np.random.seed(42)  # For reproducibility
matrix1 = np.random.randint(1, 10, (3, 3))
matrix2 = np.random.randint(1, 10, (3, 3))

# Perform matrix multiplication using np.dot
result_matrix = np.dot(matrix1, matrix2)

# Display the matrices and the result
matrix1, matrix2, result_matrix


(array([[7, 4, 8],
        [5, 7, 3],
        [7, 8, 5]]),
 array([[4, 8, 8],
        [3, 6, 5],
        [2, 8, 6]]),
 array([[ 56, 144, 124],
        [ 47, 106,  93],
        [ 62, 144, 126]]))

65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [ ]:
# Generate an array of 50 random integers between 10 and 1000
np.random.seed(42)  # For reproducibility
random_array = np.random.randint(10, 1001, 50)

# Calculate percentiles and quartiles
percentile_10 = np.percentile(random_array, 10)
percentile_50 = np.percentile(random_array, 50)  # Median
percentile_90 = np.percentile(random_array, 90)
quartile_1 = np.percentile(random_array, 25)  # First quartile (Q1)
quartile_3 = np.percentile(random_array, 75)  # Third quartile (Q3)

# Display the results
percentile_10, percentile_50, percentile_90, quartile_1, quartile_3


(107.80000000000001, 456.5, 866.4, 206.75, 694.75)

66. Create a NumPy array of integers and find the index of a specific element.

In [ ]:
# Generate a NumPy array of integers
np.random.seed(42)  # For reproducibility
num_array = np.random.randint(1, 100, 20)  # Array of 20 integers between 1 and 100

# Choose a specific element to find its index
element_to_find = num_array[5]  # Selecting an element that exists in the array

# Find the index of the specific element
index = np.where(num_array == element_to_find)[0][0]

# Display the array, the element, and its index
num_array, element_to_find, index


(array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53,  2, 88,
        30, 38,  2]),
 21,
 5)

67. Generate a random NumPy array and sort it in ascending order.

In [ ]:
# Generate a random NumPy array of 15 integers between 1 and 100
np.random.seed(42)  # For reproducibility
random_array = np.random.randint(1, 100, 15)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

# Display the original and sorted arrays
random_array, sorted_array


(array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53]),
 array([ 3, 15, 21, 22, 24, 52, 53, 61, 72, 75, 75, 83, 87, 88, 93]))

68. Filter elements >20  in the given NumPy array.arr = np.array([12, 25, 6, 42, 8, 30])

In [ ]:
# Import NumPy
import numpy as np

# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_arr = arr[arr > 20]

# Display the filtered array
filtered_arr


array([25, 42, 30])

69. Filter elements which are divisible by 3 from a given NumPy arrayarr = np.array([1, 5, 8, 12, 15])

In [ ]:
# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

# Display the filtered array
filtered_arr


array([12, 15])

70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.arr = np.array([10, 20, 30, 40, 50])


In [ ]:
# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements that are ≥ 20 and ≤ 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

# Display the filtered array
filtered_arr


array([20, 30, 40])

71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.arr = np.array([1, 2, 3])

In [ ]:
# Given NumPy array
arr = np.array([1, 2, 3])

# Check the byte order using the dtype attribute
byte_order = arr.dtype.byteorder

# Display the byte order
byte_order


'='

72. For the given NumPy array, perform byte swapping in place using `byteswap()`.arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
# Given NumPy array with specified dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(inplace=True)

# Display the modified array
arr


array([16777216, 33554432, 50331648], dtype=int32)

73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
# Given NumPy array with specified dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Display the original and swapped arrays
arr, swapped_arr


(array([1, 2, 3], dtype=int32),
 array([16777216, 33554432, 50331648], dtype='>i4'))

74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
# Given NumPy array with specified dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Check system endianness and swap byte order conditionally
if arr.dtype.byteorder == '=':  # Native byte order
    swapped_arr = arr.newbyteorder('S')  # Swap to opposite endianness
else:
    swapped_arr = arr.newbyteorder('=')  # Convert to native endianness

# Display the original and swapped arrays
arr, swapped_arr


(array([1, 2, 3], dtype=int32),
 array([16777216, 33554432, 50331648], dtype='>i4'))

75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
# Given NumPy array with specified dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary
needs_byte_swap = arr.dtype.byteorder not in ('=', '|')  # '=' means native byte order, '|' means not applicable

# Display the result
needs_byte_swap


False

76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [ ]:
# Create a NumPy array with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
arr1, copy_arr


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10]))

77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [ ]:
# Generate a 2D NumPy array (3x3) with random integers
np.random.seed(42)  # For reproducibility
matrix = np.random.randint(1, 100, (3, 3))

# Extract a slice (view) from the matrix
view_slice = matrix[:2, :2]  # Top-left 2x2 submatrix

# Modify an element in view_slice
view_slice[0, 0] = 999

# Display the original matrix and the view slice
matrix, view_slice


(array([[999,  93,  15],
        [ 72,  61,  21],
        [ 83,  87,  75]]),
 array([[999,  93],
        [ 72,  61]]))

78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [ ]:
# Create a NumPy array of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice (view) from array_a
view_b = array_a[:2, :2]  # Top-left 2x2 submatrix

# Broadcast the addition of 5 to view_b
view_b += 5

# Display the original array and the view slice
array_a, view_b


(array([[ 6,  7,  3],
        [ 9, 10,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 6,  7],
        [ 9, 10]]))

79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [ ]:
# Create a NumPy array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view of shape (4, 2)
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 999

# Display the original array and the reshaped view
orig_array, reshaped_view


(array([[999,   2,   3,   4],
        [  5,   6,   7,   8]]),
 array([[999,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8]]))

80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [ ]:
# Generate a NumPy array (3x4) with random integers between 1 and 10
np.random.seed(42)  # For reproducibility
data = np.random.randint(1, 11, (3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in data_copy
data_copy[0] = 999

# Display the original array and the modified copy
data, data_copy


(array([[ 7,  4,  8,  5],
        [ 7, 10,  3,  7],
        [ 8,  5,  4,  8]]),
 array([999,   8,   7,  10,   7,   8,   8]))

81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [ ]:
# Create two matrices A and B of identical shape (3x3) with random integers
np.random.seed(42)  # For reproducibility
A = np.random.randint(1, 20, (3, 3))
B = np.random.randint(1, 20, (3, 3))

# Perform addition and subtraction
sum_matrix = A + B
diff_matrix = A - B

# Display the matrices and results
A, B, sum_matrix, diff_matrix


(array([[ 7, 15, 11],
        [ 8,  7, 19],
        [11, 11,  4]]),
 array([[ 8,  3,  2],
        [12,  6,  2],
        [ 1, 12, 12]]),
 array([[15, 18, 13],
        [20, 13, 21],
        [12, 23, 16]]),
 array([[-1, 12,  9],
        [-4,  1, 17],
        [10, -1, -8]]))

82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [ ]:
# Create two matrices C (3x2) and D (2x4) with random integers
np.random.seed(42)  # For reproducibility
C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))

# Perform matrix multiplication
result_matrix = np.dot(C, D)

# Display the matrices and result
C, D, result_matrix


(array([[7, 4],
        [8, 5],
        [7, 3]]),
 array([[7, 8, 5, 4],
        [8, 8, 3, 6]]),
 array([[ 81,  88,  47,  52],
        [ 96, 104,  55,  62],
        [ 73,  80,  44,  46]]))

83. Create a matrix `E` and find its transpose.

In [ ]:
# Create a matrix E (3x3) with random integers
np.random.seed(42)  # For reproducibility
E = np.random.randint(1, 20, (3, 3))

# Compute the transpose of E
E_transpose = E.T

# Display the original matrix and its transpose
E, E_transpose


(array([[ 7, 15, 11],
        [ 8,  7, 19],
        [11, 11,  4]]),
 array([[ 7,  8, 11],
        [15,  7, 11],
        [11, 19,  4]]))

84. Generate a square matrix `F` and compute its determinant.

In [ ]:
import numpy as np

# Create a square matrix F (3x3) with random integers
np.random.seed(42)  # For reproducibility
F = np.random.randint(1, 10, (3, 3))

# Compute the determinant of F
det_F = np.linalg.det(F)

# Display the matrix and its determinant
F, det_F


(array([[7, 4, 8],
        [5, 7, 3],
        [7, 8, 5]]),
 -11.00000000000003)

85. Create a square matrix `G` and find its inverse.

In [ ]:
# Create a square matrix G (3x3) with random integers
np.random.seed(42)  # For reproducibility
G = np.random.randint(1, 10, (3, 3))

# Compute the inverse of G
G_inverse = np.linalg.inv(G)

# Display the matrix and its inverse
G, G_inverse


(array([[7, 4, 8],
        [5, 7, 3],
        [7, 8, 5]]),
 array([[-1.        , -4.        ,  4.        ],
        [ 0.36363636,  1.90909091, -1.72727273],
        [ 0.81818182,  2.54545455, -2.63636364]]))